// FDG fidelity audit, MVP.
// Generated/started: 2026-07-03.
// Repo HEAD at audit start: 693bae8 cleanup.
// Relevant history snapshot:
//   693bae8 2026-07-03 cleanup
//   9512cbe 2026-07-03 draft as default + makefile
//   413cbff 2026-07-02 fixes
//   a1006ad 2026-07-02 fmt
//   c9e554f 2026-07-02 add license, typos
//   cfa1f68 2026-07-02 Merge commit 'e1481748...' as 'fdg-book'
//   e148174 2026-07-02 Squashed 'fdg-book/' content from commit 9beb699
//   9edbac7 2026-07-02 Initial commit

#set document(
  title: "FDG PDF / Org / Typst Audit",
  author: "fdgtyp audit",
)
#set page(paper: "us-letter", margin: (x: 0.72in, y: 0.72in))
#set text(font: "New Computer Modern", size: 10pt)
#set par(justify: true, leading: 0.56em)
#show heading: set block(above: 1.1em, below: 0.45em)
#show raw.where(block: true): set block(
  fill: rgb("#f7f7f2"),
  inset: 7pt,
  radius: 3pt,
  width: 100%,
)

#let tag(label, fill) = box(
  fill: fill,
  stroke: rgb("#555555"),
  inset: (x: 4pt, y: 2pt),
  radius: 2pt,
)[#text(size: 7pt, weight: "bold")[#label]]

#let partial = tag("PARTIAL", rgb("#fff4c2"))
#let unchecked = tag("UNCHECKED", rgb("#eeeeee"))
#let known = tag("KNOWN", rgb("#d7f0df"))
#let risk = tag("RISK", rgb("#ffd9d4"))
#let target = tag("TARGET", rgb("#dce9ff"))
#let st-exact = tag("EXACT", rgb("#cfead6"))
#let st-partial-exact = tag("PARTIAL-EXACT", rgb("#e7f1bf"))
#let st-accepted = tag("ACCEPTED-STYLISTIC", rgb("#dbe9ff"))
#let st-source-drift = tag("SOURCE-DRIFT", rgb("#ffd8b5"))
#let st-pdf-repair = tag("PDF-DERIVED-REPAIR", rgb("#e7d9ff"))
#let st-project-added = tag("PROJECT-ADDED", rgb("#d7f3ee"))
#let st-bug = tag("BUG", rgb("#ffc6c6"))
#let st-unchecked = tag("UNCHECKED", rgb("#eeeeee"))

= FDG PDF / Org / Typst Audit

This standalone file is a starter audit comparing three artifacts:

- Published PDF: `fdg-book/fdg_book.pdf`
- Upstream Org/source material: `fdg-book/scheme/org/*.org`
- Current Typst book output: `fdg-book.pdf`

The goal is not to claim full fidelity yet. The goal is to make every partial comparison visible, so later audit runs can turn each partial or unchecked row into an exhaustive row without losing the evidence trail.

Project decisions recorded after the MVP:

- Letter layout is intentional; page-for-page reproduction of the published PDF is not a goal.
- Errata in the current book PDF is intentional project end matter.
- `typ/main.pdf` and `fdg-book.pdf` are expected to differ only by cover/index material.
- This audit should remain a standalone Typst document.
- Reference numbers should match the published PDF where possible. Current implementation seeds citation order invisibly from the published reference list, while keeping generated bibliography output.

== Audit Labels

#table(
  columns: (1.1in, auto),
  stroke: 0.4pt,
  inset: 5pt,
  [#known], [Evidence is concrete enough to rely on for future work.],
  [#partial], [Some representative source/PDF/Typst evidence has been checked, but not the whole region.],
  [#unchecked], [Inventory exists, but no meaningful comparison has been completed yet.],
  [#risk], [Likely fidelity gap or known difference that needs action.],
  [#target], [What a later exhaustive pass should produce.],
)

Audit entry statuses are color-coded separately from coverage labels:

#table(
  columns: (1.65in, auto),
  stroke: 0.4pt,
  inset: 5pt,
  [#st-exact], [Checked exhaustively for the stated region and matches the chosen target.],
  [#st-partial-exact], [Sampled or scoped evidence matches, but the claim is not exhaustive.],
  [#st-accepted], [Intentional style/layout difference; not a bug unless content is obscured or lost.],
  [#st-source-drift], [Org/source differs from the published PDF or chosen canonical text.],
  [#st-pdf-repair], [Typst intentionally repairs or reconstructs content from the published PDF.],
  [#st-project-added], [Intentional project-specific material outside the published PDF body target.],
  [#st-bug], [Actionable defect in conversion, source, layout, or output.],
  [#st-unchecked], [Not meaningfully checked yet.],
)

== Inputs and Build Facts

#table(
  columns: (1.45in, 1.45in, 1.45in, auto),
  stroke: 0.4pt,
  inset: 5pt,
  [Artifact], [Path], [Observed metadata], [Audit note],
  [Published PDF], [`fdg-book/fdg_book.pdf`], [249 pages; 432 x 639.36 pt; Acrobat Distiller; modified 2017-01-16.], [Canonical visual/text target for book body and published index.],
  [Current book PDF], [`fdg-book.pdf`], [170 pages; US letter; Typst 0.15.0.], [Generated by `make book`; includes intentional cover/index/errata material.],
  [Draft PDF], [`typ/main.pdf`], [167 pages; US letter; Typst 0.15.0.], [Generated by `make draft`; expected to differ from `fdg-book.pdf` only by cover/index material.],
  [Org source], [`fdg-book/scheme/org/*.org`], [19 Org files at top level.], [`fdg.org` currently includes only preface, prologue, and chapter 1; the converter/book assembly uses the individual content files directly.],
  [Typst source], [`typ/content/*.typ`], [18 content files.], [Generated from Org plus repo-specific repairs and presentation support.],
)

Reproduction commands used for this MVP:

```text
pdfinfo fdg-book/fdg_book.pdf
pdfinfo fdg-book.pdf
pdfinfo typ/main.pdf
pdftotext -f 1 -l 8 fdg-book/fdg_book.pdf -
pdftotext -f 1 -l 8 fdg-book.pdf -
pdftotext -f 230 -l 249 fdg-book/fdg_book.pdf -
pdftotext -f 160 -l 170 fdg-book.pdf -
rg -n '^(=+|#fdg-chapter)' typ/content/*.typ
rg -n '^\\*+ ' fdg-book/scheme/org/*.org
git log --date=short --pretty=format:'%h %ad %s' -n 20
```

== Executive Diff

#table(
  columns: (1.35in, 1.45in, 1.45in, 1.45in, auto),
  stroke: 0.4pt,
  inset: 5pt,
  [Area], [Published PDF], [Org source], [Current Typst PDF], [MVP finding],
  [Physical layout], [249 pages, small custom page size.], [No final pagination.], [170 pages, letter paper.], [#known Letter layout is intentional. Use semantic/content checks first; layout differences are accepted unless they obscure or drop content.],
  [Front matter], [LaTeX/MIT Press title, copyright, Einstein quote, contents.], [`fdg.org` has title metadata and quote.], [Custom Typst cover, title, copyright, quote, generated contents.], [#partial Main matter is aligned in order; typography and contents pagination differ.],
  [Body chapters], [Preface, prologue, chapters 1-11, appendices A-C, references, index.], [Matching chapter files exist, except `fdg.org` is not a complete driver.], [Matching Typst content files exist and are included by `typ/main.typ`.], [#partial Existing notes say every chapter/appendix has at least one published-PDF spotcheck; preface, prologue, chapters 1-2, and chapter 11 had deeper passes.],
  [End matter], [References then index.], [`references.org` and `errata.org` exist.], [References, generated index, then errata.], [#known Errata is intentionally included. The generated index is intentional, but still needs content/locator audit.],
  [References], [Published extraction begins with SICP as [1].], [Bib file follows published order.], [Current extraction begins with SICP as [1] after citation-order seeding.], [#known Numbering/order now matches sampled published references. Formatting details still need exhaustive audit.],
  [Figures], [Figures embedded in published PDF.], [Figure mentions in Org.], [8 extracted PDF assets used in Typst.], [#partial Figure inventory exists; visual placement/caption fidelity is not yet exhaustive.],
  [Code blocks], [Typeset Scheme listings and results.], [Org Scheme/result blocks.], [Typst generated fenced Scheme blocks and result text.], [#partial Known converter repairs fixed misclassified prose and cached result placeholders in early chapters. Need systematic code/result comparison.],
  [Math/equations], [Published equations are canonical when Org is empty or drifted.], [Some Org equation environments are empty or drift from PDF.], [Typst contains repaired/reconstructed equations.], [#partial Chapter 11 equations 11.1-11.14 and 11.20-11.21 were reconstructed from PDF according to existing notes.],
)

== Structural Coverage Ledger

#table(
  columns: (1.35in, 1.25in, 1.25in, auto),
  stroke: 0.4pt,
  inset: 4pt,
  [Region], [Org -> Typst], [PDF -> Typst], [Current status],
  [Preface], [#partial], [#partial], [Deep pass mentioned in `PDF-FIDELITY-NOTES.md`; needs line-level audit entries.],
  [Prologue], [#partial], [#partial], [Deep pass mentioned; Scheme/prose classification fixes already landed.],
  [Chapter 1], [#partial], [#partial], [Deep pass mentioned; Cartan noweb placeholder and cached-result placeholder issues fixed.],
  [Chapter 2], [#partial], [#partial], [Deep pass mentioned; coordinate-independence wording/formula drift fixed.],
  [Chapters 3-10], [#partial], [#partial], [At least one PDF page spotchecked per chapter; needs exhaustive section-by-section comparison.],
  [Chapter 11], [#partial], [#partial], [Deep pass mentioned; many equations reconstructed from PDF.],
  [Appendices A-C], [#partial], [#partial], [At least one PDF page spotchecked per appendix; Appendix C end sample shows semantic match but reference-number phrasing differs.],
  [References], [#partial], [#partial], [Published order is encoded in `fdg-reference-order`; sampled numbering now matches. Formatting and every entry still need exhaustive audit.],
  [Index], [#partial], [#partial], [Both PDFs contain indexes, but generated entries/page numbers differ substantially.],
  [Errata], [#known], [#known], [Intentional project end matter. Compare against Org, not against the published PDF body target.],
)

== Known Findings to Preserve

These come from `PDF-FIDELITY-NOTES.md` and should be retained as historical audit evidence, even if future passes re-check the same regions.

- #known 2026-07-02 spotcheck: one published-PDF page from each generated chapter and appendix was compared against Typst.
- #known Chapter 4 equation 4.3: missing `X_k` subscript was restored from the published PDF.
- #known Chapter 7 equation 7.9: punctuation was moved out of `mathsf{g}` so the final factor renders as `g`, followed by punctuation.
- #known Preface/prologue/chapter 1/chapter 2: a deeper pass fixed misclassified wrapped parenthetical prose, expanded `Cartan`, removed non-published cached-result placeholders, and repaired chapter 2 wording/formula drift.
- #known Chapter 11: a deeper pass reconstructed equations 11.1-11.14 and 11.20-11.21 from the PDF because the Org source has empty equation environments there.
- #known Chapter 11: fixes also covered `Einsten`, Lorentz interval terms, aligned Lorentz displays, `bar.v.double` norm notation, `make-4-tuple`, and `R^(= 1)`.
- #known `scripts/assert-typst-regressions.mjs` preserves automated regression coverage for generated Typst structure, selected PDF text expectations, figures, labels, and bibliography keys. As of this audit pass it reports: 15 targeted files, 1 PDF text file, 18 generated files, 74 global checks, 8 figures, 599 labels, and 21 bibliography keys.

== MVP Findings

=== A-001: Published PDF and Typst PDF use different layout targets #known

The published PDF is 249 pages at 432 x 639.36 pt. The current book PDF is 170 pages at US letter. This means page-number comparisons are useful only inside each artifact; they are not a direct fidelity metric between artifacts.

#target Later exhaustive layout work should audit for dropped, obscured, or badly placed content inside the letter layout. It should not attempt to reproduce the published page geometry.

=== A-002: Book assembly is not the same as `fdg.org` #known

`fdg-book/scheme/org/fdg.org` includes only:

```text
#+include: preface.org :minlevel 1
#+include: prologue.org :minlevel 1
#+include: chapter001.org :minlevel 1
```

The current Typst assembly in `typ/main.typ` includes preface, prologue, chapters 1-11, appendices A-C, references, generated index, and errata. Therefore, the meaningful Org comparison target is the set of individual content files, not `fdg.org` alone.

#target Future converter/audit tooling should record exactly which Org file produced each Typst file, including generated or manually repaired regions.

=== A-003: Current PDF intentionally includes extra project end matter #known

The published PDF end matter is references followed by index. The current Typst PDF table of contents shows references, index, and "Errata for FDG." This is an intentional project addition, not a published-PDF fidelity bug.

#target Future audit rows should compare errata against `fdg-book/scheme/org/errata.org` and `typ/content/errata.typ`, while marking it out of scope for published-PDF body matching.

=== A-004: Reference order is seeded to match the published PDF #known

Sampled published PDF references begin:

```text
[1] Harold Abelson and Gerald Jay Sussman with Julie Sussman, Structure and Interpretation of Computer Programs
[2] Harold Abelson and Andrea deSessa, Turtle Geometry
```

Before the fix, sampled current Typst PDF references began:

```text
[1] H. Abelson and A. deSessa, Turtle Geometry
[2] S. A. Papert, Mindstorms
...
[14] H. Abelson, G. J. Sussman, and J. Sussman, Structure and Interpretation of Computer Programs
```

That was a content-level difference, not just layout, because it changed citation numbers throughout the book.

The current Typst references are still generated with:

```typ
#bibliography("../references.bib", title: none, full: true, style: "ieee")
```

The numbering is now forced into published order by `fdg-reference-order` and `fdg-seed-bibliography-order()` in `typ/fdg-lib/refs.typ`, called from the cover/title page so it does not add pages. Verification samples from `fdg-book.pdf` after the change:

```text
Turtle Geometry [2]
IEEE Standard for the Scheme Programming Language [10]
Spivak, Calculus on Manifolds [17]
References: [1] Structure and Interpretation of Computer Programs
```

#target Exhaustive pass should compare every citation callout and bibliography entry against the published PDF. Remaining expected differences are bibliography formatting/style details, not numbering/order.

=== A-005: Index exists in both PDFs but is not equivalent #partial

The published PDF has a long index beginning after references, including symbol entries such as composition, derivative notation, tuple notation, and Scheme syntax entries. The current Typst PDF has a generated index with different entry set, sort behavior, page numbers, and visible generated-entry wording.

#target A full index audit should classify entries into: present in both, published-only, Typst-only, same term/different locator, and locator unavailable because page geometry intentionally differs.

=== A-006: Figures are inventoried but not visually audited #partial

Current Typst uses these extracted assets:

```text
fig-2-1.pdf
fig-2-2.pdf
fig-2-3.pdf
fig-4-1.pdf
fig-4-2.pdf
fig-5-1.pdf
fig-6-1.pdf
fig-7-1.pdf
```

The Org and Typst text mention the same figure numbers in the sampled regions. No exhaustive visual check has yet verified scaling, placement, caption punctuation, or page adjacency against the published PDF.

#target Later runs should screenshot or rasterize each figure in both PDFs, compare caption text, and mark whether visual differences are acceptable Typst styling or content loss.

=== A-007: Chapter 11 depends on PDF-derived repairs #known

Chapter 11 is a special case because the Org source contains empty equation environments for a run of published equations. The Typst source now includes reconstructed equations 11.1-11.14 and 11.20-11.21, so a naive Org-vs-Typst diff will report intentional additions.

#target Mark PDF-derived repairs inline in generated Typst or in a machine-readable sidecar, so future converter runs do not erase them silently.

== Chunk 1 Audit Entries: Front Matter and Global Rules

#table(
  columns: (0.85in, 1.25in, 1.15in, auto),
  stroke: 0.4pt,
  inset: 4pt,
  [ID], [Region], [Status], [Finding],
  [C1-001], [Artifact metadata], [#st-accepted], [Published PDF is 249 pages at 432 x 639.36 pt. Current book PDF is 170 US-letter pages. Draft PDF is 167 US-letter pages. Letter layout is intentional; page-for-page reproduction is out of scope.],
  [C1-002], [Cover/title], [#st-accepted], [Published PDF begins with a simple title leaf and title page. `fdg-book.pdf` begins with a custom Typst cover, then a title page with title/authors/MIT Press location text. `typ/main.pdf` uses a draft title leaf instead of the custom cover. This is intentional.],
  [C1-003], [Copyright/CIP], [#st-partial-exact], [Current book and draft PDFs preserve the copyright, Creative Commons license text, MIT Press sales paragraph, Computer Modern/LaTeX statement, Library of Congress data, ISBN, subject lines, classification, control number, and print line. Extraction differs in punctuation/ligatures/underscore handling, but no content loss was found in the sampled front matter.],
  [C1-004], [Einstein quote], [#st-accepted], [The quote text and attribution are present. Published PDF renders visible quotation marks around the passage; current Typst uses a quote block without literal enclosing quotation marks. Treat as accepted styling unless visual inspection later shows ambiguity.],
  [C1-005], [Contents], [#st-accepted], [Published contents is less granular and uses published pagination. Current Typst contents is generated from headings, includes more subsections/exercises, and uses Typst page numbers. Ordering is coherent and no missing top-level region was found in the sampled contents.],
  [C1-006], [Page numbering], [#st-accepted], [Current Typst sets front matter to roman numerals after title pages, then resets chapter 1 to Arabic page 1. Absolute and roman page numbers differ from the published PDF because layout and contents granularity differ intentionally.],
  [C1-007], [Draft vs book], [#known], [`typ/main.pdf` has 167 pages and starts with a draft title leaf. `fdg-book.pdf` has 170 pages and starts with the custom cover. The expected difference is cover/index material; both include the intentional errata material.],
  [C1-008], [Errata policy], [#st-project-added], [Errata appears in the current Typst outputs and is intentional project end matter. It should be compared against `fdg-book/scheme/org/errata.org` and `typ/content/errata.typ`, not treated as published-PDF body drift.],
  [C1-009], [Index policy], [#st-project-added], [`fdg-book.pdf` includes a generated index; `typ/main.pdf` omits it. Published PDF includes an index, but page locators cannot match exactly because page geometry differs intentionally. Future index audit should compare entry coverage and locator policy rather than exact page equality.],
)

Chunk 1 front-matter follow-up findings:

#table(
  columns: (0.85in, 1.35in, 1.15in, auto),
  stroke: 0.4pt,
  inset: 4pt,
  [ID], [Region], [Status], [Finding / requested correction],
  [C1-010], [License banner], [#st-bug], [The current Typst copyright page is missing the Creative Commons `CC BY-NC-SA` banner/mark from the desired front matter treatment. Record as a visual/content fidelity issue; no implementation change made in this audit pass.],
  [C1-011], [MIT Press sales email], [#st-bug], [`special_sales@mitpress.mit.edu` should be set as raw/monospace text. `creativecommons.org` should remain in the main text font, which is currently correct.],
  [C1-012], [LaTeX logo], [#st-exact], [`LaTeX` is rendered stylistically with the expected baseline offsets via the `metalogo` import. This is correct and should be preserved.],
  [C1-013], [CIP heading spacing], [#st-bug], [There should be additional vertical space before `Library of Congress Cataloging-in-Publication Data`. Current front matter needs visual spacing adjustment.],
  [C1-014], [CIP `p. cm.` line], [#st-bug], [The `p. cm.` line should be indented relative to the surrounding Cataloging-in-Publication lines.],
  [C1-015], [Print line], [#st-bug], [The final print-number line `10 9 8 7 6 5 4 3 2 1` should have wider spacing between numbers than the current Typst rendering.],
  [C1-016], [Classification punctuation], [#st-bug], [`516.3'6--dc23` should use an em dash before `dc23`, matching the published/CIP typography more closely.],
  [C1-017], [Control number alignment], [#st-bug], [`2012042107` should be right-aligned on the copyright/CIP page.],
)

Chunk 1 evidence commands:

```text
pdftotext -f 1 -l 10 fdg-book/fdg_book.pdf -
pdftotext -f 1 -l 10 fdg-book.pdf -
pdftotext -f 1 -l 8 typ/main.pdf -
pdfinfo fdg-book/fdg_book.pdf
pdfinfo fdg-book.pdf
pdfinfo typ/main.pdf
sed -n '1,140p' typ/fdg-lib/title.typ
sed -n '1,120p' typ/main.typ
```

== Exhaustive Audit Plan

For each region, future runs should append entries in this form:

```text
ID:
Region:
Source span:
Published PDF span:
Typst span:
Status: EXACT | PARTIAL-EXACT | ACCEPTED-STYLISTIC | SOURCE-DRIFT | PDF-DERIVED-REPAIR | PROJECT-ADDED | BUG | UNCHECKED
Evidence:
Decision:
Follow-up:
Commit(s):
```

The exhaustive audit should proceed in bounded chunks. Each chunk should update this file with concrete entries and leave any unfinished work explicitly marked #partial or #unchecked.

#table(
  columns: (0.8in, 1.55in, 2.1in, auto),
  stroke: 0.4pt,
  inset: 4pt,
  [Chunk], [Scope], [Deliverable], [Notes],
  [1], [Front matter and global rules], [Cover/title/copyright/quote, contents, page numbering, draft/book differences, errata/index policy.], [Mostly accepted layout/style differences. Confirm no content is dropped or obscured.],
  [2], [References and citations], [All 21 bibliography entries plus all citation callouts.], [High priority because references affect the whole text. Numbering/order now matches samples; formatting still needs audit.],
  [3], [Preface, prologue, chapters 1-2], [First full prose/math/code/footnote workflow.], [These regions already had deeper prior passes, so they are ideal for validating the audit method.],
  [4], [Chapters 3-5], [Section-by-section audit, including equations, code/results, figures through 5.1.], [Covers vector fields, basis fields, and integration.],
  [5], [Chapters 6-8], [Equation-number audit, code/result alignment, figures 6.1 and 7.1, known chapter 7 fix verification.], [Math/code density is high; keep entries section-scoped before drilling into individual blocks.],
  [6], [Chapters 9-11], [Metrics, Hodge star/electrodynamics, special relativity, chapter 11 PDF-derived repairs.], [Explicitly verify equations 11.1-11.14 and 11.20-11.21 against the published PDF.],
  [7], [Appendices A-C], [Code/prose fidelity, citations, Appendix C tensor equation/reference checks.], [Appendices are source-heavy and benefit from a separate pass.],
  [8], [Index and errata], [Generated index comparison policy; errata compared against Org/Typst source.], [Index page locators cannot match exactly because page geometry intentionally differs.],
)

Recommended workflow for each chunk:

1. Extract normalized text from the published PDF, Org source, generated Typst source, and current `fdg-book.pdf`.
2. Compare first at section level, then split mismatching sections into prose, equation, code, figure, footnote, citation, and index/reference entries.
3. Classify each mismatch as `EXACT`, `ACCEPTED-STYLISTIC`, `SOURCE-DRIFT`, `PDF-DERIVED-REPAIR`, `PROJECT-ADDED`, `BUG`, or `UNCHECKED`.
4. Fix clear bugs immediately when they are local and low risk; otherwise leave an audit entry with evidence and follow-up.
5. Rebuild `fdg-book.pdf` and `typ/audit.pdf`, then record verification evidence in this file.

== Settled Decisions and Remaining Questions

- Settled: letter layout is intentional.
- Settled: errata is intentional project end matter.
- Settled: `typ/main.pdf` and `fdg-book.pdf` should differ only by cover/index material.
- Settled: this audit lives as a standalone Typst document.
- Remaining: whether current generated IEEE-style bibliography formatting is acceptable now that numbering/order matches.
- Remaining: how should generated index entries be compared when page geometry intentionally differs?

== Commit Trail

#table(
  columns: (0.8in, 0.9in, auto),
  stroke: 0.4pt,
  inset: 4pt,
  [Commit], [Date], [Message],
  [`693bae8`], [2026-07-03], [cleanup],
  [`9512cbe`], [2026-07-03], [draft as default + makefile],
  [`413cbff`], [2026-07-02], [fixes],
  [`a1006ad`], [2026-07-02], [fmt],
  [`c9e554f`], [2026-07-02], [add license, typos],
  [`650114f`], [2026-07-02], [header],
  [`c7b3523`], [2026-07-02], [add cover],
  [`289a9dc`], [2026-07-02], [updates],
  [`20c5627`], [2026-07-02], [fmt links],
  [`e12283d`], [2026-07-02], [fmt],
  [`4eef47d`], [2026-07-02], [fixes],
  [`eb71a72`], [2026-07-02], [refs],
  [`8ed9337`], [2026-07-02], [add references],
  [`4460b9f`], [2026-07-02], [fix],
  [`3128ce4`], [2026-07-02], [cleanup],
  [`67eefdb`], [2026-07-02], [init],
  [`cfa1f68`], [2026-07-02], [Merge commit `e1481748be83c493edfe54271d2068577aef1e2d` as `fdg-book`],
  [`e148174`], [2026-07-02], [Squashed `fdg-book/` content from commit `9beb699`],
  [`9edbac7`], [2026-07-02], [Initial commit],
)
