#import "@preview/in-dexter:0.7.2": index, make-index

#let fdg-code-index(term) = index(
  term,
  display: raw(term, lang: "scheme"),
  apply-casing: false,
)

#let fdg-indexed-body(body) = {
  show "Abuse of notation": it => [#index("Abuse of notation")#it]
  show "Access chain": it => [#index("Access chain")#it]
  show "Ampere": it => [#index("Ampere")#it]
  show "Angular momentum": it => [#index("Angular momentum")#it]
  show "Arguments": it => [#index("Arguments")#it]
  show "Arithmetic": it => [#index("Arithmetic")#it]
  show "Atlas": it => [#index("Atlas")#it]
  show "Basis fields": it => [#index("Basis fields")#it]
  show "Bianchi identity": it => [#index("Bianchi identity")#it]
  show "Boost": it => [#index("Boost")#it]
  show "Cardioid": it => [#index("Cardioid")#it]
  show "Cartan one-forms": it => [#index("Cartan one-forms")#it]
  show "Chain rule": it => [#index("Chain rule")#it]
  show "Christoffel coefficients": it => [#index("Christoffel coefficients")#it]
  show "Circular orbit": it => [#index("Circular orbit")#it]
  show "Closed form field": it => [#index("Closed form field")#it]
  show "Coefficient functions": it => [#index("Coefficient functions")#it]
  show "Combinatory logic": it => [#index("Combinatory logic")#it]
  show "Comma": it => [#index("Comma")#it]
  show "Commutator": it => [#index("Commutator")#it]
  show "Components of the velocity": it => [#index("Components of the velocity")#it]
  show "Composition": it => [#index("Composition")#it]
  show "Compound data": it => [#index("Compound data")#it]
  show "Conditionals": it => [#index("Conditionals")#it]
  show "Connection": it => [#index("Connection")#it]
  show "Constraint": it => [#index("Constraint")#it]
  show "Constructors": it => [#index("Constructors")#it]
  show "Contraction": it => [#index("Contraction")#it]
  show "Contravariant": it => [#index("Contravariant")#it]
  show "Coordinate basis": it => [#index("Coordinate basis")#it]
  show "Coordinate component functions": it => [#index("Coordinate component functions")#it]
  show "Coordinate function": it => [#index("Coordinate function")#it]
  show "Coordinate independence": it => [#index("Coordinate independence")#it]
  show "Coordinate patch": it => [#index("Coordinate patch")#it]
  show "Coordinate representation": it => [#index("Coordinate representation")#it]
  show "Coordinate transformations": it => [#index("Coordinate transformations")#it]
  show "Cosmology": it => [#index("Cosmology")#it]
  show "Coulomb": it => [#index("Coulomb")#it]
  show "Covariant": it => [#index("Covariant")#it]
  show "Covariant derivative": it => [#index("Covariant derivative")#it]
  show "Curvature": it => [#index("Curvature")#it]
  show "Currying": it => [#index("Currying")#it]
  show "Derivative": it => [#index("Derivative")#it]
  show "Determinant": it => [#index("Determinant")#it]
  show "Differential": it => [#index("Differential")#it]
  show "Differential equation": it => [#index("Differential equation")#it]
  show "Dimension of manifold": it => [#index("Dimension of manifold")#it]
  show "Directional derivative": it => [#index("Directional derivative")#it]
  show "Divergence Theorem": it => [#index("Divergence Theorem")#it]
  show "Down tuple": it => [#index("Down tuple")#it]
  show "Dual basis": it => [#index("Dual basis")#it]
  show "Duality": it => [#index("Duality")#it]
  show "Einstein": it => [#index("Einstein")#it]
  show "Electrodynamics": it => [#index("Electrodynamics")#it]
  show "Empty list": it => [#index("Empty list")#it]
  show "Euler angles": it => [#index("Euler angles")#it]
  show "Euler-Lagrange equations": it => [#index("Euler-Lagrange equations")#it]
  show "Event": it => [#index("Event")#it]
  show "Evolution": it => [#index("Evolution")#it]
  show "Evolution operator": it => [#index("Evolution operator")#it]
  show "Exact form field": it => [#index("Exact form field")#it]
  show "Exponentiating Lie derivatives": it => [#index("Exponentiating Lie derivatives")#it]
  show "Expressions": it => [#index("Expressions")#it]
  show "Exterior derivative": it => [#index("Exterior derivative")#it]
  show "Faraday": it => [#index("Faraday")#it]
  show "Faraday tensor": it => [#index("Faraday tensor")#it]
  show "Field equations": it => [#index("Field equations")#it]
  show "Force": it => [#index("Force")#it]
  show "Form field": it => [#index("Form field")#it]
  show "Formal parameters": it => [#index("Formal parameters")#it]
  show "Franklin": it => [#index("Franklin")#it]
  show "Friedmann metric": it => [#index("Friedmann metric")#it]
  show "Friedmann-Lemaître-Robertson-Walker": it => [#index("Friedmann-Lemaître-Robertson-Walker")#it]
  show "Function": it => [#index("Function")#it]
  show "Functional mathematical notation": it => [#index("Functional mathematical notation")#it]
  show "Fundamental Theorem of Calculus": it => [#index("Fundamental Theorem of Calculus")#it]
  show "Galileo Galilei": it => [#index("Galileo Galilei")#it]
  show "Gauss": it => [#index("Gauss")#it]
  show "General relativity": it => [#index("General relativity")#it]
  show "Generic arithmetic": it => [#index("Generic arithmetic")#it]
  show "Geodesic deviation": it => [#index("Geodesic deviation")#it]
  show "Geodesic motion": it => [#index("Geodesic motion")#it]
  show "Geometric function": it => [#index("Geometric function")#it]
  show "Geometric object": it => [#index("Geometric object")#it]
  show "Global Lorentz frame": it => [#index("Global Lorentz frame")#it]
  show "Green's Theorem": it => [#index("Green's Theorem")#it]
  show "Hamiltonian Evolution": it => [#index("Hamiltonian Evolution")#it]
  show "Hodge dual": it => [#index("Hodge dual")#it]
  show "Hodge star": it => [#index("Hodge star")#it]
  show "Integral": it => [#index("Integral")#it]
  show "Integral curve": it => [#index("Integral curve")#it]
  show "Integration": it => [#index("Integration")#it]
  show "Interior product": it => [#index("Interior product")#it]
  show "Jacobian": it => [#index("Jacobian")#it]
  show "Kronecker delta": it => [#index("Kronecker delta")#it]
  show "Lagrange equations": it => [#index("Lagrange equations")#it]
  show "Lagrangian": it => [#index("Lagrangian")#it]
  show "Lambda calculus": it => [#index("Lambda calculus")#it]
  show "Lambda expression": it => [#index("Lambda expression")#it]
  show "Laplacian": it => [#index("Laplacian")#it]
  show "Leibniz rule": it => [#index("Leibniz rule")#it]
  show "Lie derivative": it => [#index("Lie derivative")#it]
  show "Linearity": it => [#index("Linearity")#it]
  show "Lisp": it => [#index("Lisp")#it]
  show "Local names": it => [#index("Local names")#it]
  show "Lorentz": it => [#index("Lorentz")#it]
  show "Lorentz decomposition": it => [#index("Lorentz decomposition")#it]
  show "Lorentz force": it => [#index("Lorentz force")#it]
  show "Lorentz frame": it => [#index("Lorentz frame")#it]
  show "Lorentz interval": it => [#index("Lorentz interval")#it]
  show "Lorentz transformation": it => [#index("Lorentz transformation")#it]
  show "Manifold": it => [#index("Manifold")#it]
  show "Manifold function": it => [#index("Manifold function")#it]
  show "Maxwell": it => [#index("Maxwell")#it]
  show "Maxwell tensor": it => [#index("Maxwell tensor")#it]
  show "Metric": it => [#index("Metric")#it]
  show "Minkowski": it => [#index("Minkowski")#it]
  show "Minkowski metric": it => [#index("Minkowski metric")#it]
  show "Motion": it => [#index("Motion")#it]
  show "Multiplication of tuples": it => [#index("Multiplication of tuples")#it]
  show "Newton": it => [#index("Newton")#it]
  show "Non-coordinate basis": it => [#index("Non-coordinate basis")#it]
  show "Notation": it => [#index("Notation")#it]
  show "Oersted": it => [#index("Oersted")#it]
  show "One-form field": it => [#index("One-form field")#it]
  show "Operator": it => [#index("Operator")#it]
  show "Oriented area of a parallelogram": it => [#index("Oriented area of a parallelogram")#it]
  show "Over a map": it => [#index("Over a map")#it]
  show "Parallel transport": it => [#index("Parallel transport")#it]
  show "Partial derivative": it => [#index("Partial derivative")#it]
  show "Patch": it => [#index("Patch")#it]
  show "Phase-space state function": it => [#index("Phase-space state function")#it]
  show "Pullback": it => [#index("Pullback")#it]
  show "Pushforward": it => [#index("Pushforward")#it]
  show "Raising a one-form field": it => [#index("Raising a one-form field")#it]
  show "Recursive procedures": it => [#index("Recursive procedures")#it]
  show "Reparameterization": it => [#index("Reparameterization")#it]
  show "Residual": it => [#index("Residual")#it]
  show "Restricted vector field": it => [#index("Restricted vector field")#it]
  show "Ricci": it => [#index("Ricci")#it]
  show "Ricci scalar": it => [#index("Ricci scalar")#it]
  show "Ricci tensor": it => [#index("Ricci tensor")#it]
  show "Riemann": it => [#index("Riemann")#it]
  show "Riemann curvature": it => [#index("Riemann curvature")#it]
  show "Riemann curvature operator": it => [#index("Riemann curvature operator")#it]
  show "Riemann tensor": it => [#index("Riemann tensor")#it]
  show "Rotation": it => [#index("Rotation")#it]
  show "Schwarzschild spacetime": it => [#index("Schwarzschild spacetime")#it]
  show "Selector": it => [#index("Selector")#it]
  show "SO(3)": it => [#index("SO(3)")#it]
  show "Spacelike": it => [#index("Spacelike")#it]
  show "Spacetime": it => [#index("Spacetime")#it]
  show "Special orthogonal group": it => [#index("Special orthogonal group")#it]
  show "Special relativity": it => [#index("Special relativity")#it]
  show "Spherical surface": it => [#index("Spherical surface")#it]
  show "State derivative": it => [#index("State derivative")#it]
  show "Stereographic projection": it => [#index("Stereographic projection")#it]
  show "Stokes's Theorem": it => [#index("Stokes's Theorem")#it]
  show "Stress-energy tensor": it => [#index("Stress-energy tensor")#it]
  show "Structure constants": it => [#index("Structure constants")#it]
  show "Subscripts": it => [#index("Subscripts")#it]
  show "Superscripts": it => [#index("Superscripts")#it]
  show "Symbolic values": it => [#index("Symbolic values")#it]
  show "Syntactic sugar": it => [#index("Syntactic sugar")#it]
  show "Tensor": it => [#index("Tensor")#it]
  show "Timelike": it => [#index("Timelike")#it]
  show "Tuple": it => [#index("Tuple")#it]
  show "Vector": it => [#index("Vector")#it]
  show "Vector calculus": it => [#index("Vector calculus")#it]
  show "Vector field": it => [#index("Vector field")#it]
  show "Vector field over a map": it => [#index("Vector field over a map")#it]
  show "Vector integral theorems": it => [#index("Vector integral theorems")#it]
  show "Velocity": it => [#index("Velocity")#it]
  show "Volume": it => [#index("Volume")#it]
  show "Walking on a sphere": it => [#index("Walking on a sphere")#it]
  show "Wave equation": it => [#index("Wave equation")#it]
  show "Wedge product": it => [#index("Wedge product")#it]
  show "Zero-based indexing": it => [#index("Zero-based indexing")#it]

  // Scheme procedures and coordinate-system names from the original index.
  show "basis->1form-basis": it => [#fdg-code-index("basis->1form-basis")#it]
  show "basis->vector-basis": it => [#fdg-code-index("basis->vector-basis")#it]
  show "car": it => [#fdg-code-index("car")#it]
  show "Cartan-transform": it => [#fdg-code-index("Cartan-transform")#it]
  show "cdr": it => [#fdg-code-index("cdr")#it]
  show "chart": it => [#fdg-code-index("chart")#it]
  show "Christoffel->Cartan": it => [#fdg-code-index("Christoffel->Cartan")#it]
  show "circular": it => [#fdg-code-index("circular")#it]
  show regex("component([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("component")#it]
  show "components->1form-field": it => [#fdg-code-index("components->1form-field")#it]
  show "components->vector-field": it => [#fdg-code-index("components->vector-field")#it]
  show "compose": it => [#fdg-code-index("compose")#it]
  show "cond": it => [#fdg-code-index("cond")#it]
  show "cons": it => [#fdg-code-index("cons")#it]
  show "contract": it => [#fdg-code-index("contract")#it]
  show regex("coordinate-system([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("coordinate-system")#it]
  show "coordinate-system-at": it => [#fdg-code-index("coordinate-system-at")#it]
  show "coordinate-system->basis": it => [#fdg-code-index("coordinate-system->basis")#it]
  show "coordinatize": it => [#fdg-code-index("coordinatize")#it]
  show regex("covariant-derivative([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("covariant-derivative")#it]
  show "covariant-derivative-form": it => [#fdg-code-index("covariant-derivative-form")#it]
  show "covariant-derivative-vector": it => [#fdg-code-index("covariant-derivative-vector")#it]
  show "curl": it => [#fdg-code-index("curl")#it]
  show regex("define([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("define")#it]
  show "define-coordinates": it => [#fdg-code-index("define-coordinates")#it]
  show "differential": it => [#fdg-code-index("differential")#it]
  show "div": it => [#fdg-code-index("div")#it]
  show "down": it => [#fdg-code-index("down")#it]
  show "drop2": it => [#fdg-code-index("drop2")#it]
  show "Einstein-field-equation": it => [#fdg-code-index("Einstein-field-equation")#it]
  show "else": it => [#fdg-code-index("else")#it]
  show "eq?": it => [#fdg-code-index("eq?")#it]
  show "F->C": it => [#fdg-code-index("F->C")#it]
  show "Faraday": it => [#fdg-code-index("Faraday")#it]
  show "FLRW-metric": it => [#fdg-code-index("FLRW-metric")#it]
  show "form-field->form-field-over-map": it => [#fdg-code-index("form-field->form-field-over-map")#it]
  show "g-Minkowski": it => [#fdg-code-index("g-Minkowski")#it]
  show regex("general-boost([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("general-boost")#it]
  show "general-boost2": it => [#fdg-code-index("general-boost2")#it]
  show "grad": it => [#fdg-code-index("grad")#it]
  show "lambda": it => [#fdg-code-index("lambda")#it]
  show "Lie-derivative-vector": it => [#fdg-code-index("Lie-derivative-vector")#it]
  show regex("list([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("list")#it]
  show "list-ref": it => [#fdg-code-index("list-ref")#it]
  show "literal-1form-field": it => [#fdg-code-index("literal-1form-field")#it]
  show "literal-Christoffel-2": it => [#fdg-code-index("literal-Christoffel-2")#it]
  show "literal-function": it => [#fdg-code-index("literal-function")#it]
  show "literal-manifold-function": it => [#fdg-code-index("literal-manifold-function")#it]
  show "literal-manifold-map": it => [#fdg-code-index("literal-manifold-map")#it]
  show "literal-metric": it => [#fdg-code-index("literal-metric")#it]
  show "literal-vector-field": it => [#fdg-code-index("literal-vector-field")#it]
  show regex("metric->Christoffel-2([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("metric->Christoffel-2")#it]
  show "metric->Lagrangian": it => [#fdg-code-index("metric->Lagrangian")#it]
  show "Newton-connection": it => [#fdg-code-index("Newton-connection")#it]
  show "Newton-metric": it => [#fdg-code-index("Newton-metric")#it]
  show "pullback-form": it => [#fdg-code-index("pullback-form")#it]
  show "pullback-function": it => [#fdg-code-index("pullback-function")#it]
  show "pullback-vector-field": it => [#fdg-code-index("pullback-vector-field")#it]
  show "pushforward-vector": it => [#fdg-code-index("pushforward-vector")#it]
  show "R2->R": it => [#fdg-code-index("R2->R")#it]
  show regex("R2-polar([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("R2-polar")#it]
  show "R2-polar-Cartan": it => [#fdg-code-index("R2-polar-Cartan")#it]
  show regex("R2-rect([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("R2-rect")#it]
  show "R2-rect-Cartan": it => [#fdg-code-index("R2-rect-Cartan")#it]
  show "R2-rect-Christoffel": it => [#fdg-code-index("R2-rect-Christoffel")#it]
  show "R2-rect-point": it => [#fdg-code-index("R2-rect-point")#it]
  show "R3-cyl": it => [#fdg-code-index("R3-cyl")#it]
  show "raise": it => [#fdg-code-index("raise")#it]
  show "ref": it => [#fdg-code-index("ref")#it]
  show "Riemann-curvature": it => [#fdg-code-index("Riemann-curvature")#it]
  show "series:for-each": it => [#fdg-code-index("series:for-each")#it]
  show "SO3-metric": it => [#fdg-code-index("SO3-metric")#it]
  show regex("sphere-Cartan([^A-Za-z0-9_-]|$)"): it => [#fdg-code-index("sphere-Cartan")#it]
  show "sphere->R3": it => [#fdg-code-index("sphere->R3")#it]
  show "spherical-metric": it => [#fdg-code-index("spherical-metric")#it]
  show "square": it => [#fdg-code-index("square")#it]
  show "Tdust": it => [#fdg-code-index("Tdust")#it]
  show "tensor-test": it => [#fdg-code-index("tensor-test")#it]
  show "trace2down": it => [#fdg-code-index("trace2down")#it]
  show "up": it => [#fdg-code-index("up")#it]
  show "vector-basis->dual": it => [#fdg-code-index("vector-basis->dual")#it]

  body
}

#let fdg-index-page() = {
  pagebreak()
  heading(level: 1, numbering: none, outlined: true)[Index]

  quote(block: true)[
    Any inaccuracies in this index may be explained by the fact that it has been prepared with the help of a computer.

    Donald E. Knuth, Fundamental Algorithms (Volume 1 of The Art of Computer Programming)
  ]

  text(size: 9pt)[
    Page numbers for Scheme procedure definitions are included with the generated entries.
  ]

  columns(3, gutter: 1.2em)[
    #set text(size: 8.8pt)
    #make-index(title: none, use-page-counter: true)
  ]
}
