// Generated by ../scripts/convert-org-to-typst.mjs.
// Edit typ/lib.typ for presentation; edit the converter for structural changes.

#import "lib.typ": *
#import "index.typ": fdg-indexed-body, fdg-index-page

// For a manual test, replace this line with:
// #let code-edition = "clojure" // "scheme", "clojure", or "both"
#let code-edition = sys.inputs.at("code", default: "scheme")
#show: fdg-book.with(code-edition: code-edition)

#fdg-title-page(
  seed: fdg-seed-bibliography-order(),
  code-edition: code-edition,
)

#set page(numbering: "i")

#outline(title: "Contents")
#pagebreak()

#fdg-indexed-body[
  #if code-edition in ("clojure", "both") [
    #include "content/preface_cljs.typ"
  ]
  #include "content/preface.typ"
  #include "content/prologue.typ"
  #pagebreak()
  #set page(numbering: "1")
  #counter(page).update(1)
  #include "content/chapter001.typ"
  #include "content/chapter002.typ"
  #include "content/chapter003.typ"
  #include "content/chapter004.typ"
  #include "content/chapter005.typ"
  #include "content/chapter006.typ"
  #include "content/chapter007.typ"
  #include "content/chapter008.typ"
  #include "content/chapter009.typ"
  #include "content/chapter010.typ"
  #include "content/chapter011.typ"
  #[
    #counter(heading).update(0)
    #set heading(numbering: "A.1", supplement: [Appendix])
    #include "content/appendix_a.typ"
    #include "content/appendix_b.typ"
    #include "content/appendix_c.typ"
    #if code-edition in ("clojure", "both") [
      #include "content/appendix_d.typ"
      #include "content/appendix_e.typ"
      #include "content/appendix_f.typ"
      #include "content/appendix_g.typ"
      #include "content/appendix_h.typ"
      #include "content/appendix_i.typ"
    ]
  ]
  #include "content/errata.typ"
  #include "content/references.typ"
]

#set page(numbering: "1")
#fdg-index-page()
