#set document(title: [Scheme–ClojureScript output comparison])
#set page(margin: 22mm)
#set text(size: 10pt)

= Scheme–ClojureScript output comparison

This report is generated by #raw(lang: "sh", "node scripts/compare-scm-cljs-outputs.mjs"). It compares captured ClojureScript/Emmy results with the historical scmutils result comments next to the same source blocks. Printer aliases, exact ratios, commutative ordering, and algebraic rearrangements that agree at nine deterministic substitution points are treated as equivalent.

Compared #170 positions having outputs from both systems: #170 mechanically equivalent, #0 mathematically different, and #0 unresolved. The #49 missing comparison counterparts are excluded from these totals and listed separately below. Among the equivalent pairs, #1 have CLJS output at least 1.5 times and 120 characters longer than the Scheme output. Unresolved entries are not called differences because prose or truncated output cannot safely establish unequal mathematical content.

= Equivalent but disproportionately verbose

These pairs passed the mathematical checks, but the CLJS rendering is much longer. This usually means scmutils simplified automatically while Emmy needs an explicit #raw(lang: "clojure", "simplify") around the result-producing expression. They remain passing comparisons; this is a maintainability and typesetting warning.

#table(
  columns: (1.25fr, 1.25fr, 4fr),
  inset: 6pt,
  stroke: rgb("#c7cdd4"),
  table.header(
    table.cell(fill: rgb("#fff3bf"))[*Block*],
    table.cell(fill: rgb("#fff3bf"))[*Status*],
    table.cell(fill: rgb("#fff3bf"))[*Best diagnosis*],
  ),
  table.cell(fill: rgb("#fff3bf"))[#raw("chapter009-013:1")],
[#raw("Equivalent; verbose")],
[#raw("This form already uses simplify. Emmy has expanded the three-halves power into repeated square-root factors, so a stronger canonicalization rule or assumptions may be needed rather than another wrapper.")],
)

== chapter009-013, output 1

CLJS is 494 characters versus 304 for Scheme (1.6×). This form already uses simplify. Emmy has expanded the three-halves power into repeated square-root factors, so a stronger canonicalization rule or assumptions may be needed rather than another wrapper.

Scheme/scmutils:

```scheme
(down
(/ (+ (* (((expt D 2) x) t) (expt ((D y) t) 2))
(* -1 ((D x) t) ((D y) t) (((expt D 2) y) t)))
(expt (+ (expt ((D x) t) 2) (expt ((D y) t) 2)) 3/2))
(/ (+ (* -1 (((expt D 2) x) t) ((D x) t) ((D y) t))
(* (expt ((D x) t) 2) (((expt D 2) y) t)))
(expt (+ (expt ((D x) t) 2) (expt ((D y) t) 2)) 3/2)))
```

ClojureScript/Emmy:

```scheme
(down
(/ (+ (* -1 ((D x) t) ((D y) t) (((expt D 2) y) t))
(* (((expt D 2) x) t) (expt ((D y) t) 2)))
(+ (* (expt ((D x) t) 2) (sqrt (+ (expt ((D x) t) 2) (expt ((D y) t) 2))))
(* (expt ((D y) t) 2) (sqrt (+ (expt ((D x) t) 2) (expt ((D y) t) 2))))))
(/ (+ (* (expt ((D x) t) 2) (((expt D 2) y) t))
(* -1 ((D x) t) (((expt D 2) x) t) ((D y) t)))
(+ (* (expt ((D x) t) 2) (sqrt (+ (expt ((D x) t) 2) (expt ((D y) t) 2))))
(* (expt ((D y) t) 2) (sqrt (+ (expt ((D x) t) 2) (expt ((D y) t) 2)))))))
```

= Confirmed mathematical differences

None.
None found.

= Missing comparison counterparts

49 positions either have a result on only one side or only a qualitative Scheme placeholder. They are kept separate because they do not represent failed mathematical comparisons.

#table(
  columns: (1.25fr, 1.25fr, 4fr),
  inset: 6pt,
  stroke: rgb("#c7cdd4"),
  table.header(
    table.cell(fill: rgb("#dbeafe"))[*Block*],
    table.cell(fill: rgb("#dbeafe"))[*Status*],
    table.cell(fill: rgb("#dbeafe"))[*Best diagnosis*],
  ),
  table.cell(fill: rgb("#dbeafe"))[#raw("prologue-004:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("prologue-005:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter001-005:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter001-010:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter001-012:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter001-013:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter001-017:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter001-017:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter002-004:1")],
[#raw("No CLJS capture")],
[#raw("The Scheme block contains apparent output but CLJS has no corresponding capture. Best guess: the form is deliberately non-executable, was classified as setup/definition, or still needs per-form capture support.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter003-010:1")],
[#raw("No CLJS capture")],
[#raw("The Scheme block contains apparent output but CLJS has no corresponding capture. Best guess: the form is deliberately non-executable, was classified as setup/definition, or still needs per-form capture support.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter003-020:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter003-020:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter005-009:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter005-009:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter005-014:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter005-014:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-003:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-003:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-011:1")],
[#raw("No CLJS capture")],
[#raw("The Scheme block contains apparent output but CLJS has no corresponding capture. Best guess: the form is deliberately non-executable, was classified as setup/definition, or still needs per-form capture support.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-012:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-012:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-025:1")],
[#raw("No CLJS capture")],
[#raw("The Scheme block contains apparent output but CLJS has no corresponding capture. Best guess: the form is deliberately non-executable, was classified as setup/definition, or still needs per-form capture support.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-026:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-026:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-037:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter007-039:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-013:1")],
[#raw("Qualitative Scheme placeholder")],
[#raw("The Scheme side records only a qualitative placeholder such as ‘mess’, so there is no mathematical datum to compare.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-014:1")],
[#raw("Qualitative Scheme placeholder")],
[#raw("The Scheme side records only a qualitative placeholder such as ‘mess’, so there is no mathematical datum to compare.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-019:1")],
[#raw("Printed values not returned")],
[#raw("The inner expression is now simplified and prints four zeros, matching Scheme, but the smoke runner captures only the outer for-each return value nil. Treat this as a capture-shape gap, not a mathematical mismatch.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-019:2")],
[#raw("No CLJS capture")],
[#raw("The ports expose different numbers of result-producing forms. Best guess: block merging or definition/output classification changed the alignment; inspect the forms individually before comparing by position.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-019:3")],
[#raw("No CLJS capture")],
[#raw("The ports expose different numbers of result-producing forms. Best guess: block merging or definition/output classification changed the alignment; inspect the forms individually before comparing by position.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-019:4")],
[#raw("No CLJS capture")],
[#raw("The ports expose different numbers of result-producing forms. Best guess: block merging or definition/output classification changed the alignment; inspect the forms individually before comparing by position.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-035:1")],
[#raw("No CLJS capture")],
[#raw("The Scheme block contains apparent output but CLJS has no corresponding capture. Best guess: the form is deliberately non-executable, was classified as setup/definition, or still needs per-form capture support.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-037:1")],
[#raw("No CLJS capture")],
[#raw("The Scheme block contains apparent output but CLJS has no corresponding capture. Best guess: the form is deliberately non-executable, was classified as setup/definition, or still needs per-form capture support.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter008-038:1")],
[#raw("No CLJS capture")],
[#raw("The Scheme block contains apparent output but CLJS has no corresponding capture. Best guess: the form is deliberately non-executable, was classified as setup/definition, or still needs per-form capture support.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter009-019:1")],
[#raw("Qualitative Scheme placeholder")],
[#raw("The Scheme side records only a qualitative placeholder such as ‘mess’, so there is no mathematical datum to compare.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter009-024:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter009-024:2")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter009-024:3")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("chapter009-029:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("appendix_a-003:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("appendix_b-019:2")],
[#raw("No CLJS capture")],
[#raw("The ports expose different numbers of result-producing forms. Best guess: block merging or definition/output classification changed the alignment; inspect the forms individually before comparing by position.")],
table.cell(fill: rgb("#dbeafe"))[#raw("appendix_b-023:1")],
[#raw("No Scheme reference")],
[#raw("The CLJS runner captures a value for which the book stores no historical scmutils output. This needs an oracle or manual review, not textual comparison.")],
table.cell(fill: rgb("#dbeafe"))[#raw("appendix_c-005:1")],
[#raw("Qualitative Scheme placeholder")],
[#raw("The Scheme side records only a qualitative placeholder such as ‘mess’, so there is no mathematical datum to compare.")],
table.cell(fill: rgb("#dbeafe"))[#raw("errata-024:1")],
[#raw("No CLJS capture")],
[#raw("These are explanatory errata comments, not evaluator results; the block is deliberately non-executable.")],
table.cell(fill: rgb("#dbeafe"))[#raw("errata-024:2")],
[#raw("No CLJS capture")],
[#raw("These are explanatory errata comments, not evaluator results; the block is deliberately non-executable.")],
table.cell(fill: rgb("#dbeafe"))[#raw("errata-024:3")],
[#raw("No CLJS capture")],
[#raw("These are explanatory errata comments, not evaluator results; the block is deliberately non-executable.")],
table.cell(fill: rgb("#dbeafe"))[#raw("errata-024:4")],
[#raw("No CLJS capture")],
[#raw("These are explanatory errata comments, not evaluator results; the block is deliberately non-executable.")],
table.cell(fill: rgb("#dbeafe"))[#raw("errata-024:5")],
[#raw("No CLJS capture")],
[#raw("These are explanatory errata comments, not evaluator results; the block is deliberately non-executable.")],
)

= Other unresolved comparisons

0 positions have results on both sides but cannot yet be compared safely.

None.

