(((divergence spherical-metric orthonormal-spherical-basis) v)
 R3-spherical-point)
;; (+ (((partial 0) vˆ0) (up r0 theta0 phi0))
;;    (/ (* 2 (vˆ0 (up r0 theta0 phi0))) r0)
;;    (/ (((partial 1) vˆ1) (up r0 theta0 phi0)) r0)
;;    (/ (* (vˆ1 (up r0 theta0 phi0)) (cos theta0))
;;       (* r0 (sin theta0)))
;;    (/ (((partial 2) vˆ2) (up r0 theta0 phi0))
;;       (* r0 (sin theta0))))

(((Laplacian spherical-metric orthonormal-spherical-basis)
  (literal-manifold-function 'f spherical))
 R3-spherical-point)
;; (+ (((partial 0) ((partial 0) f)) (up r0 theta0 phi0))
;;    (/ (* 2 (((partial 0) f) (up r0 theta0 phi0)))
;;       r0)
;;    (/ (((partial 1) ((partial 1) f)) (up r0 theta0 phi0))
;;       (expt r0 2))
;;    (/ (* (cos theta0) (((partial 1) f) (up r0 theta0 phi0)))
;;       (* (expt r0 2) (sin theta0)))
;;    (/ (((partial 2) ((partial 2) f)) (up r0 theta0 phi0))
;;       (* (expt r0 2) (expt (sin theta0) 2))))
