((((evolution 6) 'delta-t circular) (chart R2-rect))
      ((point R2-rect) (up 1 0)))
     ;; (up (+ (* -1/720 (expt delta-t 6))
     ;;        (* 1/24 (expt delta-t 4))
     ;;        (* -1/2 (expt delta-t 2))
     ;;        1)
     ;;     (+ (* 1/120 (expt delta-t 5))
     ;;        (* -1/6 (expt delta-t 3))
     ;;        delta-t))
