(((d (literal-manifold-function 'f-polar R2-polar))
         (coordinate-system->vector-basis R2-rect))
        ((point R2-polar) (up 'r 'theta)))
       ;;(down (- (* (((partial 0) f-polar) (up r theta)) (cos theta))
       ;;         (/ (* (((partial 1) f-polar) (up r theta))
       ;;               (sin theta))
       ;;            r))
       ;;      (+ (* (((partial 0) f-polar) (up r theta)) (sin theta))
       ;;         (/ (* (((partial 1) f-polar) (up r theta))
       ;;               (cos theta))
       ;;            r))
